### ISSUE TITLE
RTL_TCP ?

### ISSUE THREAD

**Issue by jeffreypkelly** [fbieberly/ORBCOMM-receiver#6]
Recording and Decoding on a MacBook Pro.
Any chance you can create a version that connects to a rtl_tcp client so that I can use a rpi with rtlsdr dongle on my network?
TY!

**Comment by fbieberly** [comment]
Hi. 
There are two solutions to this. The first, is you can try the rtl_tcp branch of this repo. It should do what you want. Instructions are in the readme: https://github.com/fbieberly/ORBCOMM-receiver/tree/rtl_tcp#real-time-recording-and-decoding-from-remote-rtl-sdr
Second option is my other implementation of this decoder. It is written in C and should work well on any 3B or later rpi. https://github.com/fbieberly/ORBCOMM-receiver-lite

Hope that works for you.

**Comment by jeffreypkelly** [comment]
TY!  Didn't notice that.
