### ISSUE TITLE
Is the pdf of the revised method of data packet calculation track available to send out?  Thank you very much！

### ISSUE THREAD

**Issue by cyqsir** [fbieberly/ORBCOMM-receiver#7]
The grey computing section mentioned in Orbcomm.pdf

**Comment by fbieberly** [comment]
I added the Serial Interface Specification Rev F document to the literature folder. You'd want to search for the "SATELLITE STATE VECTOR" section that tells how to decode the satellite's ephemeris packets. 

I used that reference in my code, so you can look at how I did it here: https://github.com/fbieberly/ORBCOMM-receiver/blob/26ab4df9c1e959cbe856add1a54ba5806e8d5232/file_decoder.py#L467
